-- USING CONCAT FUNCTION
-- USED TO COMBINE TWO or MORE VALUES IN TWO COLOUMS IN OUTPUT

-- USE BANK_DB 

-- SELECT EMP_ID , CONCAT(NAME , ' ' ,DESIG ) AS NA_DESIG
-- FROM EMPLOYEES;    

-- HERE WE WILL GET A NEW COLOUM NAMED NA_DESIG COMBING NAME AND DESIGNATION OF EMPLOYEES --



-- EXAMPLE 2
-- SUPPOSE WE WANT A COLOUM IN WHICH WE WANT TO ADD A 'KEYWORD' AND GET A NEW COLOUM 

-- SELECT NAME , CONCAT('ABCD' , " " , NAME) AS abcd_name
-- FROM EMPLOYEES ;

-- WE WILL GET A COLOUM NAMED as abcd_name in which a abcd keyword is added in front of all names prensent in name coloum




-- USING CONCAT_WS FUNCTION (WS = WORD SEPERATER)
-- BY USING CONCAT_WE , ALL THE COLOUMS WE ARE ADDING ARE SEPERATED BY A SYMBOL THAT WE HAVE TO GIVE


-- SUPPOSE I WANT TO COMBINE COLOUMS EMP_ID , NAME AND DEPT AND SEPERATED BY : 
-- SELECT CONCAT_WS( ":" , EMP_ID , NAME , DEPT)
-- FROM EMPLOYEES;

-- OUTPUT IS LIKE   EMP_ID:NAME:DEPT    (1:RAJU:LOAN)
