-- 1) USING REPLACE FUNC

-- SELECT REPLACE(EMP_ID, 1 , 101 ) AS NEW_EMP_ID , NAME , DESIG
-- FROM EMPLOYEES ;

-- HERE WE REPLACED THE 1 EMP_ID TO 101 AND GIVE THAT COLOUM NAME AS NEW_EMP_ID




-- 2) USING UPPER AND LOWER FUNC
-- USED TO CHANGE CASE OF LETTERS IN COLOUM

-- SELECT UPPER(DESIG) 
-- FROM EMPLOYEES;      
                   -- THIS WILL CHANGE DESIGNATION COLOUM TO UPPER CASE
-- SIMILARLY WE CAN USE LOWER FUNC TO CHANGE COLOUM TO LOWER CASE





-- 3) USING CHAR_LENGTH FUNC
-- I WANT TO CAL LENGTH OF ALL EMPLOYEE NAME THEN :

-- SELECT CHAR_LENGTH(NAME) AS LENGTH , NAME
-- FROM EMPLOYEES ;    
					-- HERE WE WILL GET TWO COLOUMS ONE IS LENGTH AND OTHER IS NAME 
                    
                    
                    

-- WE HAVE MANY FUNC SUCH AS 
-- LEFT(COL_NAME , 4)          THIS WILL GIVE FIRST 4 CHARACTERS IN THAT COLOUM 
-- RIGHT(COL_NAME , 2)         THIS WILL GIVE LAST 2 CHARACTERS IN THAT COLOUM
-- REPEAT(COL_NAME , 5)        THIS WILL PRINT 5 TIMES CONTENT
-- TRIM (COL_NAME)             THIS WILL REMOVE ALL BLANK SPACES IN THAT COLOUM