-- ALTER TABLE EMPLOYEES
-- ADD COLUMN
-- SALARY INT NOT NULL DEFAULT '25000';


-- INSERT INTO EMPLOYEES
-- VALUES ( 6 , 'Viresh' , 'Cashier' , 'Loan' , 50000),
-- ( 7 , 'shiv' , 'assistant' , 'IT' , 24000),
-- ( 8 , 'Swayam' , 'Associate' , 'Deposite' , 31000);


-- WE HAVE ADDED A COLUMN SALARY and some extra data IN OUR BANK DB


-- 1) USING LIMIT FUNC
-- LIMIT IS USED TO VIEW ONLY FEW RECORDS FROM THE DATABASE

-- ASSUME WE NEED ONLY FIRST 5 ROWS THEN :
-- SELECT *
-- FROM EMPLOYEES
-- LIMIT 5; 

-- ASSUME WE NEED THE DATA BETWEEN SOME RANE LIKE EMP_ID 3 TO EMP_ID 6 THEN :
-- SELECT *
-- FROM EMPLOYEES
-- LIMIT 2,4;


-- ASSUME WE WANT TO FIND MAX SALARIED EMPLOYEE THEN :
-- SELECT *
-- FROM EMPLOYEES
-- ORDER BY SALARY DESC
-- LIMIT 1;


-- 2) USING COUNT FUNC
-- IT COUNTS THE NUMBER OF RECORDS IN THE TABLE

-- SELECT COUNT(*)
-- FROM EMPLOYEES;
                     -- THIS COUNTS THE NUMBER OF ROWS IN TABLE


-- ASSUME WE HAVE TO CALCULATE EMPLOYEES IN LOAN DEPT THEN :

-- SELECT COUNT(DEPT)
-- FROM EMPLOYEES
-- WHERE DEPT = 'Loan';
                           -- OUTPUT TWO 
                           
-- ASSUME I HAVE TO FIND HOW MANY DIFFERENT DEPARTMENT ARE THERE

-- SELECT COUNT(DISTINCT DEPT)
-- FROM EMPLOYEES;
					-- THERE ARE 4 DIFF DEPATMENT
                    
-- ASSUME I HAVE TO FIND TOTAL NUMBER OF ASSOCIATE IN BANK THEN

-- SELECT COUNT(EMP_ID)
-- FROM EMPLOYEES
-- WHERE DESIG='Associate';
							-- OUTPUT 3
