-- 1) GROUP BY 

-- SELECT DEPT , COUNT(EMP_ID)
-- FROM EMPLOYEES
-- GROUP BY DEPT ;
				-- THIS GIVES DEPARTMENT AND NUMBER OF EMPLOYEES IN IT

-- ONE MORE EXAMPLE 

-- SELECT DESIG ,COUNT(EMP_ID)
-- FROM EMPLOYEES 
-- GROUP BY DESIG;
				-- THIS SHOWS DIFFERENT DESIGNATION PRESENT IN BANK AND NUMBER OF EMPLOYEES IN DESIGNATION
     
     
-- 2) MIN AND MAX FUNC
-- WE WILL GET MAXIMUN OR MINIMUN NUMBER FROM ANY PERTICULAR COLOUM 

-- SELECT MAX(SALARY)                   -- USE MIN() FOR MINIMUN SALARY
-- FROM EMPLOYEES ;       


-- SUPPOSE WE HAVE MAX SALARY WITH NAME OF THAT EMPLOYEE THEN WE HAVR TO USE SUBQUERY

-- SELECT NAME , SALARY
-- FROM EMPLOYEES
-- WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);
										-- SUBQUERY IS USED IN WHERE CLAUSE 
                                        
                                        
-- 3) SUM AND AVG FUNC 

-- SELECT SUM(SALARY)
-- FROM EMPLOYEES;

-- SELECT AVG(SALARY)
-- FROM EMPLOYEES;

-- I WANT TO FIND DEPAARTMENT WISE TOATL SALARY OF EMPLOYEES , I.E. TOTAL SALARY OF LOAN DEPT , etc
-- SELECT DEPT , SUM(SALARY) , COUNT(EMP_ID)
-- FROM EMPLOYEES
-- GROUP BY DEPT;



	