-- EXERCISE 2 --

-- performing ops on DATA WE INSERTED IN EXERCISE 1 --
-- USE BANK_DB


-- TASK 1 --
-- DISPLAY ONLY THOSE EMPLOYEES WHOS DEPATMENT IS Loan --

-- select *
-- FROM EMPLOYEES
-- WHERE DEPT = 'Loan' 



-- TASK 2 -- 
-- DISPLAY THE EMPLOYEE WHOS DESIGNATION IS MANAGER 

-- SELECT *
-- FROM EMPLOYEES
-- WHERE DESIG = 'MANAGER';



-- TASK 3 -- 
-- DSIPLAY ONLY NAME COLOUM OF EMPLOYEE WHOS EMP_ID IS 1 --

-- SELECT EMP_ID , NAME 
-- FROM EMPLOYEES
-- WHERE EMP_ID = 1;



-- TASK 4 -- 
-- UPDATE THE DEPT OF EMPLOYEE TO 'IT' WHOS EMP_ID IS 3 --

-- UPDATE EMPLOYEES
-- SET DEPT = 'IT'
-- WHERE EMP_ID = 3;



-- TASK 5 --
-- DELETE THE EMPLOYEE DATA OF EMP_ID = 2

-- DELETE FROM EMPLOYEES 
-- WHERE EMP_ID = 2;
